# Server settings (ServerProperties)
server:
  port: 8080

spring:
  application:
    name: activiti-spring-boot-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti_spring_demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    org.activiti.engine.impl.persistence.entity: trace

